Model import
Notrum666/SharpDXtest pull request #11
Opened 2023-12-20 13:16 UTC by YahimaB

2023-12-23 13:46 UTC, Notrum666 requested changes

2023-12-23 13:46 UTC, Notrum666 commented on Engine/Assets/Mesh.cs
> +    public class Mesh : BaseAsset //TODO: rename to model?
yes

2023-12-23 13:46 UTC, Notrum666 commented on Engine/Assets/Mesh.cs
> +    public class Primitive : IDisposable //TODO: rename to mesh?
yes

2023-12-23 13:46 UTC, Notrum666 commented on Engine/Assets/Material.cs
> +        public static Material Default()
change into readonly property so object is not re-created every time

2023-12-23 20:27 UTC, YahimaB commented on SharpDXtest/AssetsImport/AssetMeta.cs
>          public object ImportSettings = null;
Temp solution - more options

2023-12-24 07:46 UTC, Notrum666 approved these changes

2023-12-24 07:46 UTC, merged