Add logger
Notrum666/SharpDXtest pull request #2
Opened 2023-11-16 19:33 UTC by xbadmojox

2023-11-16 20:30 UTC, Notrum666 requested changes

2023-11-16 20:30 UTC, Notrum666 commented on SharpDXtest/Assets/Logger/Logger.cs
> +        string errorMessage = typeLog + message;
original message should not be modified, use wrappers with extra information

2023-11-16 20:30 UTC, Notrum666 commented on SharpDXtest/Assets/Logger/Logger.cs
> +        string errorMessage = "Error: " + e.ExceptionObject;
composing full error info into message makes it inseparable

2023-11-19 10:02 UTC, Notrum666 requested changes

2023-11-19 10:02 UTC, Notrum666 commented on SharpDXtest/EditorWindow.xaml.cs
> +            AppDomain.CurrentDomain.UnhandledException += CurrentDomainOnUnhandledException;
Should not be in editor for sure, move to static constructor of Logger

2023-11-19 10:02 UTC, Notrum666 commented on SharpDXtest/EditorWindow.xaml.cs
> +            Logger.CurrentDomainOnUnhandledException(sender, e);
note: direct call of event handlers is not a good practice, event handlers should be called by events

2023-11-21 22:26 UTC, xbadmojox commented on SharpDXtest/Assets/Logger/Logger.cs
> +namespace SharpDXtest.Assets.Components;
Переделал namespace, перенес в SharpDXtest.Assets.Logger

2023-11-21 22:26 UTC, xbadmojox commented on SharpDXtest/Assets/Logger/Logger.cs
> +using Exception = System.Exception;
Убрал, до этого использовал немного другую

2023-11-21 22:26 UTC, xbadmojox commented on SharpDXtest/Assets/Logger/Logger.cs
> +    private static void LogAdd(LogMessage obj)
переиминовал

2023-11-21 22:27 UTC, xbadmojox commented on SharpDXtest/Assets/Logger/Logger.cs
> +        switch (obj.Type)
Сделал да, думал до этого что буду использовать что то в свиче, но в итоге не понадобился

2023-11-21 22:43 UTC, xbadmojox commented on SharpDXtest/EditorWindow.xaml.cs
> +            AppDomain.CurrentDomain.UnhandledException += CurrentDomainOnUnhandledException;
Поправил

2023-11-21 22:43 UTC, xbadmojox commented on SharpDXtest/EditorWindow.xaml.cs
> +            Logger.CurrentDomainOnUnhandledException(sender, e);
Поправил

2023-11-21 23:01 UTC, Notrum666 approved these changes
Approved

2023-11-21 23:08 UTC, merged